name: CI Pipeline

on:
  push:
    branches:
      - docker_ci

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python src/train.py

      - name: Build Docker image
        run: |
          docker build -t mlops-housing-model .

      - name: Run Docker container (inference test)
        run: |
          docker run --rm -v ${{ github.workspace }}/src:/app/src mlops-housing-model python src/predict.py

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag mlops-housing-model <your-dockerhub-username>/mlops-housing-model
          docker push <your-dockerhub-username>/mlops-housing-model